apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-app
  labels:
    app: tech-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge
  template:
    metadata:
      labels:
        app: tech-challenge
    spec:
      containers:
      - name: tech-challenge
        image: tech-challenge:latest # Será substituído pelo CI/CD
        ports:
        - containerPort: 3000
          name: http
        env:
        # ConfigMap values
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: tech-challenge-config
              key: NODE_ENV
        - name: DB_PG_PORT
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secrets
              key: DB_PG_PORT
        - name: DB_PG_NAME
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secrets
              key: DB_PG_NAME
        - name: DB_PG_LOGGING
          valueFrom:
            configMapKeyRef:
              name: tech-challenge-config
              key: DB_PG_LOGGING
        - name: JWT_ACCESS_TOKEN_EXPIRATION_TIME
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secrets
              key: JWT_ACCESS_TOKEN_EXPIRATION_TIME
        - name: JWT_REFRESH_TOKEN_EXPIRATION_TIME
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secrets
              key: JWT_REFRESH_TOKEN_EXPIRATION_TIME
        # Secret values
        - name: DB_PG_HOST
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secrets
              key: DB_PG_HOST
        - name: DB_PG_USER
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secrets
              key: DB_PG_USER
        - name: DB_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secrets
              key: DB_PG_PASSWORD
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secrets
              key: API_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tech-challenge-secrets
              key: JWT_SECRET
# Variáveis de ambiente configuradas via ConfigMap e Secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
