apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-loadbalancer
  labels:
    app: tech-challenge
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: tech-challenge
